name: "datawise-build-npm"
description: "datawise build npm"
inputs:
  NODE_VERSION:
    required: true
runs:
  using: "composite"
  steps:

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ inputs.NODE_VERSION }}
        registry-url: 'https://npm.pkg.github.com'

    - name: Cache node modules
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.OS }}-node-
          ${{ runner.OS }}-

    - name: npm install
      shell: bash
      run: npm ci --prefer-offline --cache-dir=.npm install

    - name: npm run build
      shell: bash
      run: npm --cache-dir=.npm run build
      env:
        CI: false
