name: "datawise-build-npm"
description: "datawise build npm"
inputs:
  NODE_VERSION:
    required: true
  CI:
    required: false
    default: false
runs:
  using: "composite"
  steps:

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ inputs.NODE_VERSION }}
        registry-url: 'https://npm.pkg.github.com'

    - name: Cache node modules
      id: cache-npm
      uses: actions/cache@v3
      env:
          cache-name: cache-node-modules2
      with:
        path: |
          ~/.npm
          ${{ github.workspace }}/node_modules
          ${{ github.workspace }}/.next/cache
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-


    - name: node version
      shell: bash
      run: node --version

    - name: npm version
      shell: bash
      run: npm --version

    - name: npm install
      shell: bash
      run: npm ci --prefer-offline --cache-dir=.npm
      if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}

    - name: List the state of node modules
      shell: bash
      continue-on-error: true
      run: npm list

    - name: npm run build
      shell: bash
      run: npm --cache-dir=.npm run build
      env:
        CI: ${{ inputs.CI }}
